version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "10100:5432"